FROM node:14-slim AS build

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm install

COPY . .

RUN ["npm", "run", "build"]

##########

FROM nginx:stable

COPY --from=build /usr/src/app/build /usr/share/nginx/html

RUN ["rm", "/etc/nginx/conf.d/default.conf"]

COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
