version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    env_file: ./config/dev.env
    ports:
      - "8080:8080"
    command: 
      - start-dev
    networks:
      - mern-app
  react-app:
    image: react-app
    build: ./client/
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - "./client:/usr/src/app"
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    build: ./server/
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - "./server/:/usr/src/app"
      - /usr/src/app/node_modules
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local