version: "3"
services:
  react-app:
    image: react-app-production
    build: ./client
    env_file: ./client/config/production.env
    restart: unless-stopped
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: api-server
    env_file: ./server/config/production.env
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
